# Generated by Django 5.2.7 on 2025-10-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('position', models.CharField(choices=[('manager', 'manager'), ('developer', 'developer'), ('hr', 'hr')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
    ]
